name: Publish to Maven Central

on:
  push:
    branches:
      - staging  # Triggers on any push to staging (i.e. after a PR merge)
      - 57-gitaction-to-auto-publish-maven-artefacts # Just for testing
  workflow_dispatch: # Allow manual triggering from GitHub

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Generate OpenAPI classes
        run: ./gradlew openApiGenerate

      - name: Build and Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: ./gradlew publish
